-- VieGeo Supabase Admin Support Tables
-- Run this whole script in Supabase SQL Editor.
-- It is safe to run multiple times; it only creates missing tables/columns.

begin;

-- 1) Users
create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    role text not null default 'user',
    created_at timestamptz not null default now()
);

alter table public.users add column if not exists roles text[] not null default array['user']::text[];
alter table public.users add column if not exists active_role text not null default 'user';
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists name text;
alter table public.users add column if not exists gender text;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists password text;
alter table public.users add column if not exists last_active timestamptz;
alter table public.users add column if not exists last_active_client bigint not null default 0;
alter table public.users add column if not exists force_logout boolean not null default false;
alter table public.users add column if not exists account_status text not null default 'free';
alter table public.users add column if not exists xp integer not null default 0;
alter table public.users add column if not exists score integer not null default 0;
alter table public.users add column if not exists gems integer not null default 500;
alter table public.users add column if not exists hearts integer not null default 3;
alter table public.users add column if not exists current_streak integer not null default 0;
alter table public.users add column if not exists last_active_date date;
alter table public.users add column if not exists user_name text;
alter table public.users add column if not exists grade text;
alter table public.users add column if not exists selected_grade text;
alter table public.users add column if not exists selected_difficulty text default 'easy';
alter table public.users add column if not exists game_state jsonb;
alter table public.users add column if not exists legacy_data jsonb not null default '{}'::jsonb;
alter table public.users add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_users_email on public.users (email);
create index if not exists idx_users_role on public.users (role);
create index if not exists idx_users_score on public.users (score desc);

update public.users
set user_name = coalesce(nullif(trim(user_name), ''), nullif(trim(name), ''), nullif(trim(full_name), ''), split_part(email, '@', 1))
where user_name is null or trim(user_name) = '';

update public.users
set score = xp
where score = 0 and xp > 0;

create or replace function public.sync_user_ranking_fields()
returns trigger
language plpgsql
as $$
begin
    if new.user_name is null or trim(new.user_name) = '' then
        new.user_name := coalesce(nullif(trim(new.name), ''), nullif(trim(new.full_name), ''), split_part(new.email, '@', 1));
    end if;
    if tg_op = 'INSERT' and coalesce(new.score, 0) = 0 then
        new.score := coalesce(new.xp, 0);
    elsif tg_op = 'UPDATE' and new.xp is distinct from old.xp and new.score is not distinct from old.score then
        new.score := coalesce(new.xp, 0);
    end if;
    return new;
end;
$$;

do $$
begin
    if not exists (select 1 from pg_trigger where tgname = 'trg_sync_user_ranking_fields') then
        create trigger trg_sync_user_ranking_fields
        before insert or update on public.users
        for each row execute function public.sync_user_ranking_fields();
    end if;
end
$$;

-- 2) Premium requests
create table if not exists public.premium_requests (
    id bigint generated by default as identity primary key,
    user_email text not null,
    status text not null default 'pending',
    created_at timestamptz not null default now()
);

alter table public.premium_requests add column if not exists email text;
alter table public.premium_requests add column if not exists name text;
alter table public.premium_requests add column if not exists reviewed_at timestamptz;
alter table public.premium_requests add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_premium_requests_user_email on public.premium_requests (user_email);
create index if not exists idx_premium_requests_status on public.premium_requests (status);
create index if not exists idx_premium_requests_created_at on public.premium_requests (created_at desc);

-- 3) Submissions
create table if not exists public.submissions (
    id bigint generated by default as identity primary key,
    user_email text not null,
    score numeric not null default 0,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.submissions add column if not exists province text;
alter table public.submissions add column if not exists island text;
alter table public.submissions add column if not exists topic text;
alter table public.submissions add column if not exists correct_count integer;
alter table public.submissions add column if not exists total_count integer;

create index if not exists idx_submissions_user_email on public.submissions (user_email);
create index if not exists idx_submissions_created_at on public.submissions (created_at desc);

-- 4) User feedbacks
create table if not exists public.user_feedbacks (
    id bigint generated by default as identity primary key,
    user_email text not null,
    content text not null,
    created_at timestamptz not null default now()
);

alter table public.user_feedbacks add column if not exists subject text;
alter table public.user_feedbacks add column if not exists message text;
alter table public.user_feedbacks add column if not exists sender_id text;
alter table public.user_feedbacks add column if not exists sender_name text;
alter table public.user_feedbacks add column if not exists status text not null default 'pending';
alter table public.user_feedbacks add column if not exists created_at_client bigint;

create index if not exists idx_user_feedbacks_user_email on public.user_feedbacks (user_email);
create index if not exists idx_user_feedbacks_created_at on public.user_feedbacks (created_at desc);
create index if not exists idx_user_feedbacks_status on public.user_feedbacks (status);

-- 5) Error reports
create table if not exists public.error_reports (
    id bigint generated by default as identity primary key,
    error_message text not null,
    page text,
    created_at timestamptz not null default now()
);

alter table public.error_reports add column if not exists user_email text;
alter table public.error_reports add column if not exists content text;
alter table public.error_reports add column if not exists subject text;
alter table public.error_reports add column if not exists message text;
alter table public.error_reports add column if not exists sender_id text;
alter table public.error_reports add column if not exists sender_name text;
alter table public.error_reports add column if not exists status text not null default 'pending';
alter table public.error_reports add column if not exists created_at_client bigint;
alter table public.error_reports add column if not exists resolved_at timestamptz;
alter table public.error_reports add column if not exists resolved_at_client bigint;
alter table public.error_reports add column if not exists resolved_by text;

create index if not exists idx_error_reports_user_email on public.error_reports (user_email);
create index if not exists idx_error_reports_status on public.error_reports (status);
create index if not exists idx_error_reports_created_at on public.error_reports (created_at desc);
create index if not exists idx_error_reports_resolved_at on public.error_reports (resolved_at desc);

-- Development-friendly permissions for the current browser-based anon client.
-- For production, replace these broad grants/RLS-disabled settings with proper
-- authenticated policies.
alter table public.users disable row level security;
alter table public.premium_requests disable row level security;
alter table public.submissions disable row level security;
alter table public.user_feedbacks disable row level security;
alter table public.error_reports disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.users to anon, authenticated;
grant select, insert, update, delete on table public.premium_requests to anon, authenticated;
grant select, insert, update, delete on table public.submissions to anon, authenticated;
grant select, insert, update, delete on table public.user_feedbacks to anon, authenticated;
grant select, insert, update, delete on table public.error_reports to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

commit;
